### ISSUE TITLE
@rezzz: @xiaoluoboding @beehiiv @SubstackInc @Revue @Ghost @ConvertKit @MailerLite @Mailchimp Hope you arent using Revue unless youre moving off

### ISSUE THREAD

**Issue by xiaoluoboding** [xiaoluoboding/t-to-g#229]
@rezzz: @xiaoluoboding @beehiiv @SubstackInc @Revue @Ghost @ConvertKit @MailerLite @Mailchimp Hope you aren&rsquo;t using Revue unless you&rsquo;re moving off<br>
via Twitter https://twitter.com/rezzz/status/1607536807905824769<br>
December 27, 2022 at 08:40AM

**Comment by RezzZ** [comment]
?
